//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direktor
    {
        public decimal JmbgDir { get; set; }
        public string ImeDir { get; set; }
        public string PrezDir { get; set; }
        public decimal BolnicaBolnicaId { get; set; }
    
        public virtual Bolnica Bolnica { get; set; }
    }
}
